#!/bin/sh

# npx prettier -c $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g' 2>&1 >/dev/null)
# [ $? -ne 0 ] && exit $?
# exit 0

# ==== check svelte, ts and js ====

DIFF_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$DIFF_FILES" ] && exit 0

# Check if there are any non-compliant files
PRETTIER_FILES=$(echo "$DIFF_FILES" | xargs npx prettier --ignore-unknown --list-different | sed 's| |\\ |g')
[ -z "$PRETTIER_FILES" ] && exit 0

printf "The following files are non-compliant to the prettier config.\n"
echo $PRETTIER_FILES | sed -E 's|([^\\]) |\1\n|g'

printf "Run \`npm run fmt\` to format all files automatically or use\n"
printf "\`npm run fmt:check\` to see full list of unformatted files in\nproject root.\n"

# ==== check rust ====

# ---- fmt ----
RUST_FMT_FILES=$(echo $FILES | xargs cargo fmt --check --manifest-path src-tauri/Cargo.toml -- --files-with-diff)
[ -z $RUST_FMT_FILES ] && exit 0

printf "The following files are non-compliant to the rustfmt config.\n"
echo $PRETTIER_FILES | sed -E 's|([^\\]) |\1\n|g'

printf "Run \`npm run rs-fmt\` to format all files automatically or use\n"
printf "\`npm run rs-fmt:check\` to see full list of unformatted files in\nproject root.\n"

# ---- lint ----


# ---- clippy ----

exit 1

