site_name: gitgauge
nav:
- Home: 'index.md'
- Guide: 'guide/getting-started.md'
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  palette:
    - scheme: slate
      primary: black
      accent: teal
  font:
    text: "DM Mono"
    code: "DM Mono"

plugins:
  - search
  - macros:
      include_dir: macros
      module_name: main

watch:
  - data
  - macros

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - md_in_html
