site_name: gitgauge
repo_name: 2025W1-Commitment
repo_url: "https://github.com/Monash-FIT3170/2025W1-Commitment"
nav:
- Home: 'index.md'
- Guide: 'guide/getting-started.md'
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  palette:
    - scheme: slate
      primary: black
      accent: teal
  font:
    text: "DM Mono"
    code: "DM Mono"

plugins:
  - search
  - macros:
      module_name: tools/main

watch:
  - data

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - md_in_html
