site_name: gitgauge
repo_name: 2025W1-Commitment
repo_url: "https://github.com/Monash-FIT3170/2025W1-Commitment"
nav:
- Home: 'index.md'
- Guide: 'guide/getting-started.md'
- Releases: 
    # BEGIN AUTO-RELEASES
      - All releases: releases/index.md
      - v0.8.0: releases/v0.8.0.md
      - v0.7.2: releases/v0.7.2.md
      - v0.7.1: releases/v0.7.1.md
      - v0.7.0: releases/v0.7.0.md
      - v0.6.1: releases/v0.6.1.md
      - v0.6.0: releases/v0.6.0.md
      - v0.5.0: releases/v0.5.0.md
      - v0.4.0: releases/v0.4.0.md
      - v0.3.1: releases/v0.3.1.md
      - v0.3.0: releases/v0.3.0.md
      - gitgauge-v0.6.0: releases/gitgauge-v0.6.0.md
    # END AUTO-RELEASES
    
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  palette:
    - scheme: slate
      primary: black
      accent: teal
  font:
    text: "DM Mono"
    code: "DM Mono"

plugins:
  - search
  - awesome-pages
  - macros:
      module_name: tools/main

watch:
  - docs/data

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - md_in_html
