    name: Deploy MkDocs Site

    on:
      workflow_dispatch:
        inputs:
          publish:
            description: "Commit & deploy"
            type: boolean
            default: false
      push:
        branches:
          - main
      release:
        types: [ created, edited, published ]

    permissions:
      contents: write

    jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
              ref: ${{ github.ref }}

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: 3.13

          - name: Configure Git Credentials
            run: |
              git config user.name github-actions[bot]
              git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          - name: Install MkDocs and Theme
            run: pip install -r docs/requirements.txt

          - name: Sync docs/data/releases.yml from latest GitHub Release
            env:
              GH_REPO: Monash-FIT3170/2025W1-Commitment
              GG_YAML_PATH: docs/data/releases.yml
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: python docs/tools/update-releases.py

          - name: Commit releases.yml if changed
            run: |
              if git diff --quiet -- docs/data/releases.yml; then
                echo "No changes to releases.yml"
              else
                git add docs/data/releases.yml
                git commit -m "chore: sync releases.yml from latest GitHub Release"
                git push
              fi

          - name: Deploy MkDocs Site
            run: cd docs;mkdocs gh-deploy --force
