    name: Deploy MkDocs Site

    on:
      push:
        branches:
          - main

    permissions:
      contents: write

    jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: 3.13

          - name: Configure Git Credentials
            run: |
              git config user.name github-actions[bot]
              git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          - name: Enter docs directory
            run: cd docs
          - name: Install MkDocs and Theme
            run: pip install -r requirements.txt
          - name: Deploy MkDocs Site
            run: mkdocs gh-deploy --force
